language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t northernjay/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true northernjay/react-test npm test

after_success:
  - docker build -t northernjay/multi-client ./client
  - docker build -t northernjay/multi-nginx ./nginx
  - docker build -t northernjay/multi-server ./server
  - docker build -t northernjay/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push northernjay/multi-client
  - docker push northernjay/multi-nginx
  - docker push northernjay/multi-server
  - docker push northernjay/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-east-1
#   app: multi-docker
#   env: Multidocker-env
#   bucket_name: elasticbeanstalk-us-east-1-040745076844
#   bucket_path: docker-multi
#   on:
#     branch: main
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY